name: Build Landing page

on:
  push:
    branches:
      - master
    paths:
      - "landing/*"
      - "landing/*/*"

jobs:
  landing-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1

      - name: Minify the landing page
        run: npx html-minifier landing/index.html --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true -o landing/index.html
      - name: Minify the privacy page
        run: npx html-minifier landing/privacy/index.html --collapse-whitespace --remove-comments --remove-optional-tags --remove-redundant-attributes --remove-script-type-attributes --remove-tag-whitespace --use-short-doctype --minify-css true --minify-js true -o landing/privacy/index.html

      - name: Deploy to the gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./landing
